### ISSUE TITLE
[TabNine] Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

### ISSUE THREAD

**Issue by youssefavx** [codota/tabnine-atom#20]
I'm running TabNine on Atom. It was working fine for a long while but I started getting these errors from Atom as I was typing (sort of these red hint boxes which show up every once in a while, with that error message). 

It seems to still be working fine, but for some reason the errors don't stop.

MacOS Mojave 10.14

**Comment by dimacodota** [comment]
Hi @youssefavx,
could you please open the dev tools (View -> Developer -> Toggle Developer Tools) and attach the stack trace logs?

**Comment by youssefavx** [comment]
Hey @dimacodota 
If you mean the console, here's what I see: 

```
Loading Emmet extensions from ~/emmet
/Users/youssefavx/.atom/packages/emmet/lib/emmet.coffee:139 

Loading Emmet extensions from 
/Users/youssefavx…ib/emmet.coffee:156 
Emmet: no such extension folder: /Users/youssefavx/emmet
loadExtensions @ /Users/youssefavx/.atom/packages/emmet/lib/emmet.coffee:156


'ask-stack.autoDetectLanguage' could not set the default. Attempted default: undefined; Schema: true    <embedded>:11 
setDefaults @ <embedded>:11
```

**Comment by youssefavx** [comment]
I'm also getting this error as I type too: 


```
Error: connect ECONNREFUSED 127.0.0.1:52745
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

**Comment by dimacodota** [comment]
the fix is available in TabNine beta version

you can try it by enabling the beta version:

type TabNine::config and check the "Receive beta releases of TabNine" option

**Comment by dimacodota** [comment]
fixed in v4.0.2
