### ISSUE TITLE
Mac Atom failed

### ISSUE THREAD

**Issue by northeast250** [codota/tabnine-atom#23]
Installing TabNine to /Users/admin/.atom/packages ✗

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.atom/.apm/_logs/2020-05-06T08_10_04_405Z-debug.log

**Comment by northeast250** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/admin/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/admin/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session f3ee15fa7bbd65be
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball 2799ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 2936ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Zlib.(anonymous function).onerror (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:131:21)
11 verbose stack     at Unzip.write (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:255:31)
11 verbose stack     at Unzip.flush (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:222:10)
11 verbose stack     at Unzip.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:229:10)
11 verbose stack     at Object.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:634:10)
11 verbose stack     at Object.onceWrapper (events.js:273:13)
11 verbose stack     at PassThrough.emit (events.js:187:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1090:12)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
12 verbose cwd /private/var/folders/0k/85mwpxr57174qlj_1rp3vfdh0000gq/T/apm-install-dir-12046-78330-mxgp8a.ki1u
13 verbose Darwin 19.4.0
14 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/admin/.atom/.apm/.apmrc" "--userconfig" "/Users/admin/.atom/.apmrc" "install" "https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v10.2.1
16 verbose npm  v6.2.0
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]

**Comment by dimacodota** [comment]
hey @northeast250, 
please try `npm cache clean --force`

**Comment by technobaboo** [comment]
Having the same issue on Win10 @dimacodota, `npm cache clean --force` did nothing to me. Posting log here: 
[2020-06-16T21_49_02_330Z-debug.log](https://github.com/codota/tabnine-atom/files/4789273/2020-06-16T21_49_02_330Z-debug.log)

Exact error message: 
```
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nova\.atom\.apm\_logs\2020-06-16T21_49_02_330Z-debug.log
```

**Comment by northeast250** [comment]
➜  /Users/admin npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
➜  /Users/admin apm install tabnine
Installing tabnine to /Users/admin/.atom/packages ✗

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.atom/.apm/_logs/2020-07-02T02_35_44_600Z-debug.log


  /Users/admin cat /Users/admin/.atom/.apm/_logs/2020-07-02T02_35_44_600Z-debug.log          
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/admin/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/admin/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball',
1 verbose cli   '--target=5.0.13',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose npm-session e7d08b7c1a680265
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/codota/tabnine-atom/legacy.tar.gz/v2.8.1 4180ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 4203ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Unzip.write (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:147:22)
11 verbose stack     at Unzip.flush (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:98:10)
11 verbose stack     at Unzip.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:104:10)
11 verbose stack     at Object.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/tar/lib/parse.js:421:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:672:10)
11 verbose stack     at Object.onceWrapper (events.js:286:20)
11 verbose stack     at PassThrough.emit (events.js:203:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
12 verbose cwd /private/var/folders/0k/85mwpxr57174qlj_1rp3vfdh0000gq/T/apm-install-dir-202062-83215-zpu7rq.zt1n
13 verbose Darwin 19.5.0
14 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/admin/.atom/.apm/.apmrc" "--userconfig" "/Users/admin/.atom/.apmrc" "install" "https://www.atom.io/api/packages/tabnine/versions/2.8.1/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v10.20.1
16 verbose npm  v6.14.5
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]
