### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by 4TT4** [codota/tabnine-atom#27]
Error: connect ECONNREFUSED 127.0.0.1:52146
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

**Comment by hiimdoublej** [comment]
Been getting this as well, exactly same. 
`ECONNREFUSED....(net.js:1061:14)`

**Comment by zrma** [comment]
Me too, exactly.

![image](https://user-images.githubusercontent.com/4281810/106849749-a455b380-66f6-11eb-99e9-26b503d23b42.png)

OS: Windows 10 20H2(OS build 19042.746)
Atom: 1.54.0 x64

**Comment by UncleAlone** [comment]
Same issues.
OS: MacOS Big Sur 11.2
Atom: 1.54.0 x64

**Comment by rodrigomelo9** [comment]
Same here (Debian 9, Atom). Any news? a workaround?

**Comment by wayneotweezy** [comment]
![tabnine-atom](https://user-images.githubusercontent.com/65606005/110255106-3de8dd00-7fa3-11eb-83b8-3f769578f1a4.png)
Me too, just switched to Tabnine and this is pretty disappointing, Love the program though so hope a fix will be found soon

**Comment by AppChampion** [comment]
The same applies on MacOS

**Comment by ckhatton** [comment]
Same here, for months! I was told to submit an email to support... heard nothing back.

macOS Big Sur 11.2.3
Atom 1.55.0

```
Error: connect ECONNREFUSED 127.0.0.1:63829
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

**Comment by asifaziz01** [comment]
Getting the same error on Ubuntu 20, Atom. I hope the team is working to resolve it.

**Comment by SaphiraKai** [comment]
Arch Linux, same issue here. Are you guys working on this? I effectively cannot use it in this state, and this seems like something you might want to deal with sooner rather than later

**Comment by dimacodota** [comment]
fixed in v4.0.4
