### ISSUE TITLE
Uncaught Error: Read a response from the engine before a request was written.

### ISSUE THREAD

**Issue by Nichidanil** [codota/tabnine-atom#56]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 18.04.4
**Thrown From**: [TabNine](https://github.com/codota/tabnine-atom) package 4.0.3

### Stack Trace

Uncaught Error: Read a response from the engine before a request was written.

```
At /home/danil/.atom/packages/TabNine/dist/main.js:9

Error: Read a response from the engine before a request was written.
    at /packages/TabNine/dist/main.js:9:7794)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
```

### Non-Core Packages

```
TabNine 4.0.3 
```

**Comment by dimacodota** [comment]
fixed in 4.0.7 version

**Comment by TimTinkers** [comment]
@dimacodota unfortunately I just experienced this immediately upon restarting Atom post `apm install tabnine`. I am on version 4.0.7 and using an up-to-date Arch Linux installation. Here are my developer console logs.
```
electron/js2c/renderer_init.js:15 (electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.
styles-element.coffee:82 [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
status-item.ts:8 this: class o extends HTMLElement{static initialize(){return customElements.define("tabnine-status-item",this),console.log("this:",this),this}constructor(){super(),this.classList.add("inline-block");const e=docu…
emmet.coffee? [sm]:110 Loading Emmet extensions from ~/emmet
emmet.coffee? [sm]:125 Emmet: no such extension folder: /home/tim/emmet
/home/tim/.atom/pack…/web/pusher.js:1451 WebSocket connection to 'wss://ws-mt1.pusher.com/app/f119821…?protocol=7&client=js&version=4.4.0&flash=false' failed: WebSocket is closed before the connection is established.
/home/tim/.atom/pack…etype-package.js:51 teletype: Using pusher key: f119821248b7429bece3
/home/tim/.atom/pack…etype-package.js:52 teletype: Using base URL: https://api.teletype.atom.io
index.ts:8 activeVersionPath: null
index.ts:13 existingVersion: null
14
preview-gutter.js? [sm]:67 Failed to expand color preview gutter!
/home/tim/.atom/pack…dential-cache.js:29 Falling back to storing credentials in memory. Auth tokens will only be stored for the lifetime of the current window.
runBinary.ts:11 Running binary: /home/tim/.tabnine/4.0.44/x86_64-unknown-linux-musl/TabNine ide-restart-counter=0
OnceReader.ts:13 Read a response : Opening in existing browser session. from the engine before a request was written.
OnceReader.ts:14 Uncaught Error: Read a response from the engine before a request was written.
    at Interface.<anonymous> (OnceReader.ts:14)
    at Interface.emit (events.js:223)
    at Interface._onLine (readline.js:315)
    at Interface._normalWrite (readline.js:460)
    at Socket.ondata (readline.js:172)
    at Socket.emit (events.js:223)
    at addChunk (_stream_readable.js:309)
    at readableAddChunk (_stream_readable.js:290)
    at Socket.Readable.push (_stream_readable.js:224)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181)
Binary.ts:98 Binary child process exited with code 0 signal unknown
index.ts:8 activeVersionPath: null
index.ts:13 existingVersion: /home/tim/.tabnine/4.0.44/x86_64-unknown-linux-musl/TabNine
runBinary.ts:11 Running binary: /home/tim/.tabnine/4.0.44/x86_64-unknown-linux-musl/TabNine ide-restart-counter=1
binaryValidator.ts:14 validating /home/tim/.tabnine/4.0.44/x86_64-unknown-linux-musl/TabNine timeout
```

**Comment by woropajj** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.3
**Thrown From**: [TabNine](https://github.com/codota/tabnine-atom) package 4.0.7


### Stack Trace

Uncaught Error: Read a response from the engine before a request was written.

```
At /home/kuba/.atom/packages/TabNine/dist/main.js:9

Error: Read a response from the engine before a request was written.
    at /packages/TabNine/dist/main.js:9:7763)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete 0.47.0 
autocomplete-R 0.6.0 
file-icons 2.1.47 
highlight-selected 0.17.0 
language-r 0.4.2 
linter 3.4.0 
minimap 4.40.0 
TabNine 4.0.7 
teletype 0.13.4 
wakatime 11.0.8 
```

**Comment by zeeshan595** [comment]
I just installed atom and downloaded tab nine to be greated by this error I am on Manjaro and this is my first time installing Atom and the tab nine package 

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: "Manjaro Linux"
**Thrown From**: [TabNine](https://github.com/codota/tabnine-atom) package 4.0.7


### Stack Trace

Uncaught Error: Read a response from the engine before a request was written.

```
At /home/zeeshan/.atom/packages/TabNine/dist/main.js:9

Error: Read a response from the engine before a request was written.
    at /packages/TabNine/dist/main.js:9:7763)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
     -1:32.6.0 core:cut (input.hidden-input)
     -1:31.4.0 core:paste (input.hidden-input)
     -1:30.2.0 core:select-all (input.hidden-input)
     -1:30 core:backspace (input.hidden-input)
     -1:26.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
TabNine 4.0.7 
```
